# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
