# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_job_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='tbc@email.com', max_length=64),
            preserve_default=False,
        ),
    ]
